### ISSUE TITLE
BetterButtonCustomAction successMessage no longer used

### ISSUE THREAD

**Issue by 3Dgoo** [unclecheese/silverstripe-gridfield-betterbuttons#102]
I've noticed `successMessage` is [no longer used](https://github.com/unclecheese/silverstripe-gridfield-betterbuttons/commit/a3607381923329f847d4c9880b23e0fcd5b415e0#diff-979b32a59f6c8cdd3551afb97dad8e14L620) by the `BetterButtonCustomAction` to return messages. Instead the action function return string is used as the message.

There is still [`successMessage` code in the `BetterButtonCustomAction` class](https://github.com/unclecheese/silverstripe-gridfield-betterbuttons/blob/master/code/actions/BetterButtonCustomAction.php#L124-L142), which is no longer used to set the return message. 

The read me document also shows an [example of using `setSuccessMessage`](https://github.com/unclecheese/silverstripe-gridfield-betterbuttons/blob/master/README.md#customising-the-user-experience) which no longer works:

    BetterButtonCustomAction::create('deny', 'Deny')
        ->setRedirectType(BetterButtonCustomAction::REFRESH)
        ->setSuccessMessage('Denied for publication')

Should this code be removed and documentation updated? 

I'm happy to make the changes and submit a pull request if you like.

**Comment by unclecheese** [comment]
This is an embarrassingly late response. I never updated the MX records for my email, and I've been missing 6 months of notifications from Github.

You're correct. This is no longer needed. Nice catch, and a PR would be really helpful. I've got six months of issues to catch up on. :)

**Comment by 3Dgoo** [comment]
Woo! Thanks Uncle Cheese.

**Comment by HARVS1789UK** [comment]
@unclecheese - Sorry to post in a closed issue, but I see in commit [57e7f7e99b923fe9331c98f4684d0d41da35f911](https://github.com/unclecheese/silverstripe-gridfield-betterbuttons/commit/57e7f7e99b923fe9331c98f4684d0d41da35f911) you have reverted these changes so that ```setSuccessMessage()``` etc still exists and is referenced in the README.md documentation.

Is there a reason for this? From my tests the return value of the custom action method is still currently what is used for displaying an error message, but the docs don't say that so I only knew thanks to this closed issue?

**Comment by unclecheese** [comment]
I think I did that because it was an API change, and it got tagged into a patch release, so it was breaking people's code who were using that method. 

I'll reapply the change to the master branch so it will work its way into a major release.

**Comment by dhensby** [comment]
Been caught out by this API breakage myself :(

**Comment by unclecheese** [comment]
@dhensby Keep in mind this module does not follow semver. API changes have thus far been permissible in "minor" releases, e.g. 1.2 and 1.3 are not compatible.

Needless to say, that needs to change.
