### ISSUE TITLE
Redirect to a specific tab with BetterButtonCustomAction

### ISSUE THREAD

**Issue by 3Dgoo** [unclecheese/silverstripe-gridfield-betterbuttons#103]
It would be great to be able to redirect to a specific tab with BetterButtonCustomAction.

I have tried the following:

	<?php
	
	class MyDataObject extends DataObject {
	
		private static $better_buttons_actions = array (
			'customaction'
		);
	
		public function customaction($action, $controller, $request) {
			
			$action->setRedirectURL(
				$controller->getEditLink() . '#Root_TabName'
			);
	
			return 'Success';
		}
	
	}

This correctly sets the URL but it does not go to the correct tab.

Is it possible to have this kind of functionality added in?

**Comment by unclecheese** [comment]
It would be quite a bit of work. If the custom action refreshed the browser, your example would work fine, but most of the time it's done with AJAX. You'd have to set up some sort of event listener that would respond to a header in the response, much like Pjax does. 

It sounds like something that would be easier, and perhaps cleaner, to implement with your own project JS. Just set up an entwine `onmatch` event for that tab and click it.

**Comment by 3Dgoo** [comment]
Thanks Uncle Cheese.
