### ISSUE TITLE
Force a file download from the cms with a custom betterbuttons action

### ISSUE THREAD

**Issue by IrinaStr** [unclecheese/silverstripe-gridfield-betterbuttons#120]
Hi,
first thank you for this great module. It is so easy to add custom actions to the CMS with it. There is still one action I can't get to work. I need a button in the CMS which forces a file download. I tried different solutions but always get the same error. 

My action code:
```
$file = File::find("assets/PDF/myFilepdf.pdf");

//check that the file is File and not null
if($file && $file instanceof File) {

       //get the file path
       $path = $file->getFullPath();

       //get the file data.
       $fileData = file_get_contents($path);
       $fileName = "myFilepdf.pdf";
       return SS_HTTPRequest::send_file($fileData, $fileName, 'application/pdf');
}
```

This code works perfectly in a frontend function, but just don't work with my betterbutton action in the cms.. can somebody help me?

The error:
> [Recoverable Error] Object of class SS_HTTPResponse could not be converted to string

**Comment by unclecheese** [comment]
For that, you can just use a simple `BetterButtonLink`.

```php
$fields->push(new BetterButtonLink('Download the file, "assets/myfile.pdf"));
```

**Comment by IrinaStr** [comment]
Hi unclecheese,
on clicking this button it will show me this instead of downloading the file:
![bildschirmfoto 2016-01-27 um 10 25 42](https://cloud.githubusercontent.com/assets/16084476/12609161/7b5127c0-c4e0-11e5-87dd-51bb61b9f861.png)

**Comment by IrinaStr** [comment]
Ok, I found the solution here: https://github.com/unclecheese/silverstripe-gridfield-betterbuttons/issues/64

**Comment by Taitava** [comment]
What if I want to download a dynamically generated file? For example:
```
private static $better_buttons_actions = ['DownloadFile'];

public function getBetterButtonsActions()
{
	$fields = parent::getBetterButtonsActions();
	$fields->push(BetterButtonCustomAction::create('DownloadFile', 'Download');
	return $fields;
}
public function DownloadFile()
{
	//Generate some XML content here:
	$content = $this->generateXML();

	//Make the browser download the content as a savable file
}
```

Should this be applicable just by modifying HTTP headers or does it require something more? Thanks for support! :)
