### ISSUE TITLE
BetterButtonPrevNextAction does not respect filter get variable

### ISSUE THREAD

**Issue by charles-ritchie** [unclecheese/silverstripe-gridfield-betterbuttons#129]
When generating previous and next links, any filters applied to the GridField by modelAdmin are wiped out.
I think this massively decreases the usefulness of these buttons.
E.g. Let's say the GridField is filtered by the member that created the record, this member could then quickly edit each of the records they created.

I forked and fixed this. I will place a PR referencing this issue.

**Comment by sanderha** [comment]
Any updates on if this fix will be implemented into master branch?
