### ISSUE TITLE
How are versioning buttons added

### ISSUE THREAD

**Issue by muppsy007** [unclecheese/silverstripe-gridfield-betterbuttons#157]
Readme is quite detailed, especially around creating custom buttons and actions. But I see no mention of how to add the versioning buttons (Save & Publish) functionality to a given DataObject. How does one do this?

**Comment by unclecheese** [comment]
They should be added automatically if the DataObject has the `Versioned` extension. 

But for granular control over the buttons, `getBetterButtonsActions()` is the final source of truth. If you just define that method, you can add/remove whatever you like.

**Comment by muppsy007** [comment]
Thanks mate. I wasn't aware Versioned was part of core.
