### ISSUE TITLE
Issues With Veriosn Dataobjects

### ISSUE THREAD

**Issue by thezenmonkey** [unclecheese/silverstripe-gridfield-betterbuttons#23]
When using ModelAdmin to control veriosned DataObjects, the betterbuttons override the save and publish. Save only affects the draft version

**Comment by mikeyc7m** [comment]
I have a similar issue, could be the same thing. I'm using pages that extend UserDefinedForm pages (from the UserForms module) in a ModelAdmin, the pages work fine except the form fields won't publish. It appears the BetterButtons publish button is performing an object->publish() without calling the doPublish() function of the UserDefinedForm object (which is there to publish the form fields.) 

Perhaps BetterButtons needs to check for and use any doPublish() function on the dataobject? Or should UserForms be using the onBeforePublish() hook? Not sure which is the preferred.
