### ISSUE TITLE
Incorrect "Save draft" and "Save & publish" button states

### ISSUE THREAD

**Issue by purplespider** [unclecheese/silverstripe-gridfield-betterbuttons#65]
While using BetterButtons in ModelAdmin for a SiteTree object, I've observed the following:

## For a New Record
Immediately after clicking the Add New button, the save buttons display like this:
![](http://spdr.me/g37a+) &#10007;

However, the record has **never** been saved, and isn't yet stored in the database, so the buttons should be like this:
![](http://spdr.me/7Z7P+) &#10003;

Note: There are 2 issues here:
1. Both buttons are grey with a green tick, instead of being fully green with no tick.
2. The 'Save' button says 'Saved', instead of 'Save Draft' (as it's not yet saved)

## After Clicking 'Save Draft'

I've made some edits in the WYSIWYG editor, and both buttons are correctly indicating there are changes to be saved or published:
![](http://spdr.me/7Z7P+)

However, if I click the 'Save draft' button the following is displayed:
![](http://spdr.me/g37a+) &#10007;

Note, the 'Save & publish' button has the correct title, but it is incorrectly displaying in grey with a green tick. At this state it should look like this:
![](http://spdr.me/wJ4L+)  &#10003;

**Comment by christopherdarling** [comment]
Looks like this issue may have come back, likely related to https://github.com/unclecheese/silverstripe-gridfield-betterbuttons/commit/31510b232aefa000bd04d5978f31a548bd135292

**Comment by mjvcallibrity** [comment]
Can confirm that using SilverStripe 3.1.20 and betterbuttons 1.3.10 we are seeing the problem of having incorrect states on our save and publish buttons.
