### ISSUE TITLE
Default State automatically Save and Publishes

### ISSUE THREAD

**Issue by nzstephenf** [unclecheese/silverstripe-gridfield-betterbuttons#81]
Just bringing the email as an issue here just to see if anyone else has this issue and has an idea on how to patch the problem I'm having.

Betterbuttons default state (add new) automatically Save and Publishes article pages before they are filled with data. Even if you click onto Save (and not Publish) the page is published straight away. As a side note, is there a way to integrate embargo and expiry with better buttons using the ModelAdmin function? I'm unable to have it save as draft and then publish. Only can do this using the 'Pages' section of the backend.

I'm using SilverStripe 3.1.6 with these modules mentioned above.

**Comment by unclecheese** [comment]
Does this appear to address your issue? https://github.com/unclecheese/silverstripe-gridfield-betterbuttons/pull/83

**Comment by nzstephenf** [comment]
I thought I had replied to your comment. But #83 does address what I've encounted!
