### ISSUE TITLE
New Record button steals default action

### ISSUE THREAD

**Issue by dhensby** [unclecheese/silverstripe-gridfield-betterbuttons#87]
When creating a record with BetterButtons installed, a "new record" button appears in the top right of the CMS.

When hitting the enter key to submit the form, the "new record" button is used and data is lost.

This is because the button is inserted at the top of the form - instead, it should be at the end.

Tested on Chrome 41 - windows 8.1 x64

**Comment by silverstripesk** [comment]
I can confirm this bug

**Comment by unclecheese** [comment]
This is fixed in cd6ea809f5bee80c9012c67a61614311dd27afee

**Comment by dhensby** [comment]
Thanks :)
