### ISSUE TITLE
CustomAction saving current form and setting one field

### ISSUE THREAD

**Issue by silverstripesk** [unclecheese/silverstripe-gridfield-betterbuttons#88]
Hello guys,

how to create custom action which will save actual (changed) form in modeladmin, but before save changes one field (Status) to specified number?

I have few statuses for an dataobject and i want quick "Publish" button changing Status automaticly, but without need of saving dataobject before.

Thanks!

**Comment by unclecheese** [comment]
There's a pretty clear example in the README on how to do this.

```php
    public function getBetterButtonsActions() {
        $fields = parent::getBetterButtonsActions();
        if($this->Status !== 'published') {
            $fields->push(BetterButtonCustomAction::create('publish', 'Publish'));
        }
        return $fields;
    }

    public function publish() {
        $this->Status = 'published';
        $this->write();
    }

```

**Comment by silverstripesk** [comment]
hmm, this doesn't do what I need.

Example:
I'm editing dataobject, I change Title in form, hit "Publish" button.

Result:
my edited Title is lost, but Status is changed.

How can I store current form too? Not only change status.

**Comment by unclecheese** [comment]
The custom actions don't save the form into the record. If you're specifically looking for a draft/published state, why not just add the Versioned extension to the object?

```yaml
MyDataObject:
  extensions:
    - Versioned
```

**Comment by HARVS1789UK** [comment]
@unclecheese I would also like to know if the behaviour @silverstripesk is referencing is possible. I do not want to use it for versioning/stage but I feel that almost all use cases would benefit from the other DataObject properties which have been edited should be saved (or at least have an option to make it that way).

My context for example is an ordering system in a takeaway, the custom action is 'Send to Kitchen' which updates the orders status from pending to processing (and causes it to be printed in the kitchen). Currently If the staff update anything else on the order (like customer details, payment method, ordering method, notes etc) then clicking 'Send to Kitchen' would loose all of these updates?

**Comment by unclecheese** [comment]
I see. So you're looking for something akin to "Save and send to kitchen" is that right?

**Comment by HARVS1789UK** [comment]
In this particular context yes, but I can see numerous scenarios where saving any updates made to the record before completing the custom action would be desirable and, to be honest, not many where it wouldn't.

**Comment by unclecheese** [comment]
I agree. There are some minor points to be aware of. I think there are a lot of cases where people are using custom actions without ever dirtying the form. In that case an extra `write()` is essentially harmless, but it would modify the `LastEdited` stamp, which may create undesirable effects in some cases. I supposed we could put it all in a `isChanged()` guard.

I also wonder how we would deal with versioned dataobjects. Would a custom action just save, or would it save and publish? If the user is modifying critical data and using the custom action to do something with that changed data, a publish would be necessary, but on the other hand, publishing without explicit permission to do so feels a bit dodgy.

**Comment by HARVS1789UK** [comment]
@unclecheese Your suggestion to wrap the ```write()``` call in a check for ```isChanged()``` is a good idea.

I appreciate the comments on it being difficult to tackle for versioned data objects however, in my scenario I am not versioning my Order data objects. Do you think you will be able to provide any kind of functionality for allowing custom actions to save any changes to the edit form **before** doing it's custom logic any time soon?

If not, as I need to finish the project I am using this in, I might have to remove the custom 'Send to Kitchen' action and just add a BetterButtonLInk and some custom JS which updates the relevant field(s) of my EditForm and then triggers a click of the save button instead.

Makes me feel a little sick to consider a hack like that, but I am out of ideas otherwise.
